module.exports = [
  // '**/tests/interestAccrual/TC-686.correctAccrualOnOverdrawn.test.js',
  // '**/tests/interestAccrual/TC-687.noAccrualBeforeWithdrawal.test.js',
  // '**/tests/interestAccrual/TC-688.dailyAccrualWhileInDebt.test.js',
  // '**/tests/interestAccrual/TC-689.noAccrualAfterFullRepayment.test.js',
  // '**/tests/interestAccrual/TC-690.accrualOnDrawnAmountOnly.test.js',
  // '**/tests/interestAccrual/TC-691.noAccrualWhenUnused.test.js',
  // '**/tests/interestAccrual/TC-692.interestOnlyRepayment.test.js',
  // '**/tests/interestAccrual/TC-693.partialInterestRepayment.test.js',
  // '**/tests/interestAccrual/TC-694.newDrawdownAfterRepayment.test.js',
  // '**/tests/interestAccrual/TC-817.activityLogUpdated.test.js',
  // '**/tests/interestAccrual/TC-818.glUpdated.test.js',
  // '**/tests/interestAccrual/TC-819.debtBreakdownUpdated.test.js',
  '**/tests/interestAccrual/TC-820.defaultinterest.test.js',
];