module.exports = [
  // '**/tests/manageOverdraft/TC-552.arrearsConfigurable.test.js',
  // '**/tests/manageOverdraft/TC-553-554.bucket0Stays.test.js',
  // '**/tests/manageOverdraft/bucket1/TC-555.movesToDPD1.test.js',
  // '**/tests/manageOverdraft/bucket1/TC-714.movesToBucket1.test.js',
  // '**/tests/manageOverdraft/bucket1/TC-715.staysInBucket1.test.js',
  // '**/tests/manageOverdraft/bucket1/TC-716.partialPaymentBucket1.test.js',
  '**/tests/manageOverdraft/bucket1/TC-717.fullPaymentBucket1.test.js',
  // '**/tests/manageOverdraft/bucket1/TC-718.reenableAfterRepayment.test.js',
  // '**/tests/manageOverdraft/bucket1/TC-719.bucketMovementLogged.test.js',
  // '**/tests/manageOverdraft/bucket2/TC-720.movesToBucket2.test.js',
  // '**/tests/manageOverdraft/bucket2/TC-721.staysInBucket2.test.js',
  // '**/tests/manageOverdraft/bucket2/TC-722.partialPaymentBucket2.test.js',
  // '**/tests/manageOverdraft/bucket2/TC-723.fullPaymentBucket1Only.test.js',
  // '**/tests/manageOverdraft/bucket2/TC-724.fullPaymentBucket1and2.test.js',
  // '**/tests/manageOverdraft/bucket2/TC-725.reenableAfterRepayment.test.js',
  // '**/tests/manageOverdraft/bucket2/TC-1992.bucketMovementLogged.test.js',
  // '**/tests/manageOverdraft/bucket3/TC-1993.movesToBucket3.test.js',
  // '**/tests/manageOverdraft/bucket3/TC-1994.staysInBucket3.test.js',
  // '**/tests/manageOverdraft/bucket3/TC-1995.partialPaymentBucket3.test.js',
  // '**/tests/manageOverdraft/bucket3/TC-1996.fullPaymentBucket1Only.test.js',
  // '**/tests/manageOverdraft/bucket3/TC-1997.fullPaymentBucket1and2.test.js',
  // '**/tests/manageOverdraft/bucket3/TC-1998.fullPaymentAllBuckets.test.js',
  // '**/tests/manageOverdraft/bucket3/TC-1999.reenableAfterRepayment.test.js',
  // '**/tests/manageOverdraft/bucket3/TC-2000.bucketMovementLogged.test.js',
  // '**/tests/manageOverdraft/default/TC-2001.defaultFlagAt90Days.test.js',
  // '**/tests/manageOverdraft/default/TC-2002.statusDebtDisabledDefault.test.js',
  // '**/tests/manageOverdraft/default/TC-2003.nextStatementNullInDefault.test.js',
  // '**/tests/manageOverdraft/default/TC-2004.defaultStatusLogged.test.js',
  // '**/tests/manageOverdraft/default/TC-2005.repaymentAfterDefault.test.js',
  // '**/tests/manageOverdraft/default/TC-2006.movesToBucket4.test.js',
  // '**/tests/manageOverdraft/default/TC-2007.writtenOffAt456Days.test.js',
  // '**/tests/manageOverdraft/default/TC-2008.writeOffLogged.test.js',
  // '**/tests/manageOverdraft/default/TC-2009.multiCyclePartialPayment.test.js',
];